gridboard:
  do_qualize_hist: 0
  do_smoothing: 1
  bin_type: 1
  bin_param0: 50
  bin_param1: 0
#  unitleng: 5.0
#  n_circles_x: 20
#  n_circles_y: 27
#  origin_x: 10
#  origin_y: 13
#  unitleng: 10.0
#  n_circles_x: 10
#  n_circles_y: 14
#  origin_x: 5
#  origin_y: 7
  unitleng: 10.0
  n_circles_x: 18
  n_circles_y: 27
  origin_x: 9
  origin_y: 13
  distance_between_circles: 1.2
  n_circles_minimum: 4
  min_rate: 0.33
  max_rate: 1.5
  fitscore: 0.95
  fitrange: 1.5
  torelance: 1.5

robot:
  calib:
    bTc:
      rotation:
        w: 0.977762047708
        x: -0.112881464975
        y: -0.130625758459
        z: -0.119063277939
      translation:
        x: 470.594474979
        y: -113.517667694
        z: -171.931893347
    mTc:
      rotation:
        w: 0.702056262525
        x: 6.17380128347e-05
        y: 0.0091951558474
        z: -0.712062110737
      translation:
        x: -114.249242046
        y: 40.006525588
        z: -32.598011928

volume_of_interest:
  xmin: nan #382 #387 #250
  xmax: nan #592 #567 #563
  ymin: nan #-78 #-60 #-300
  ymax: nan #228 #176 #-80
#  zmin: 10.5 #19.5 #4
  zmin: 11.5 #19.5 #4
  zmax: nan #105 #113 #99

#image_publisher:
#  file_name: /home/yoods/.ros/image.png

dense_sparse:
  threshold: 2000

solver:
  debug: 1    #write debug file True=1 False=0
  verbose: 0  #show debug window True=1 False=0
  crop_file_path: '/home/yoods/catkin_ws/src/rovi/MasterTeachMethod/sample_crop.json' #crop file path
  master_dir: '/home/yoods/catkin_ws/src/rovi/MasterTeachMethod/master/' #マスターディレクトリパス
  debug_data_dir: '/home/yoods/catkin_ws/src/rovi/MasterTeachMethod/debug_data/' #デバッグ用ファイル保存ディレクトリ
  robot_type: 'Mitsubishi' #Mitsubishi
  #robot_type: 'Funac' #Funac
  fitness_threshold: 0.5  #一致率閾値
