live:
  camera:
    ExposureTime: 30000
    Gain: 50
pshift_genpc:
  camera:
    ExposureTime: 8400
    Gain: 0
  projector:
    ExposureTime: 20
    Intencity: 120
calibration:
  bTc:
    translation:
      x: 0
      y: 0
      z: 0
    rotation:
      x: 0
      y: 0
      z: 0
      w: 1
  mTc:
    translation:
      x: 0
      y: 0
      z: 0
    rotation:
      x: 0
      y: 0
      z: 0
      w: 1
